export enum ModuleNamesToID{
    Chatclear = 1,
    Giveaway = 2,
    Reactrole = 3,
    Spamfilter = 4,
    Speaksupport = 5,
    Ticketsupport = 6,
    Joinmessage = 7,
    Aiospamfilter = 8,
    Streamer = 9,
    Aioclientfilter = 10,
    AntiBot = 11,
    AntiNuke = 12,
    Antirole = 13,
    publicmetrics = 14,
}

export enum ModuleNames{
    Chatclear = "chatclear",
    Giveaway = "giveaway",
    Reactrole = "reactrole",
    Spamfilter = "spamfilter",
    Speaksupport = "speaksupport",
    Ticketsupport = "ticketsupport",
    Joinmessage = "joinmessage",
    Aiospamfilter = "aiospamfilter",
    Streamer = "streamer",
    Aioclientfilter = "aioclientfilter",
    AntiBot = "antibot",
    AntiNuke = "antinuke",
    Antirole = "antirole",
    publicmetrics = "publicmetrics",
}