name: run AIO-Bot
on: [push]

jobs:
  aiopush:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm outdated
        continue-on-error: true
      - run: npm audit
        continue-on-error: true
      - run: npm run test